# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."changedetection" = {
    image = "ghcr.io/dgtlmoon/changedetection.io";
    volumes = [
      "changedetection_changedetection-data:/datastore:rw"
    ];
    ports = [
      "5000:5000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=changedetection"
      "--network-alias=changedetection"
      "--network=changedetection_default"
    ];
  };
  systemd.services."podman-changedetection" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-changedetection_default.service"
      "podman-volume-changedetection_changedetection-data.service"
    ];
    requires = [
      "podman-network-changedetection_default.service"
      "podman-volume-changedetection_changedetection-data.service"
    ];
    partOf = [
      "podman-compose-changedetection-root.target"
    ];
    wantedBy = [
      "podman-compose-changedetection-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-changedetection_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f changedetection_default";
    };
    script = ''
      podman network inspect changedetection_default || podman network create changedetection_default
    '';
    partOf = [ "podman-compose-changedetection-root.target" ];
    wantedBy = [ "podman-compose-changedetection-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-changedetection_changedetection-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect changedetection_changedetection-data || podman volume create changedetection_changedetection-data
    '';
    partOf = [ "podman-compose-changedetection-root.target" ];
    wantedBy = [ "podman-compose-changedetection-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-changedetection-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
