# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_acpi" ];
  boot.initrd.kernelModules = [ "brcmfmac" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "intel_idle.max_cstate=1" ];

  boot.initrd.prepend = [ "${./acpi_override}" ];
  boot.kernelPatches = [
    {
      name = "acpi_upgrade";
      patch = null;
      extraConfig = ''
        ACPI_TABLE_UPGRADE y
      '';
    }
  ];

  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;
  hardware.firmware = [
    (pkgs.callPackage ./brcm.nix {})
  ];

  boot.loader = {
    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot";
    };
    grub = {
      efiSupport = true;
      device = "nodev";
    };
  };

  fileSystems."/" = lib.mkForce
    { device = "/dev/disk/by-uuid/7ee757e6-4f50-4681-9b5b-27c2cb1f84e4";
      fsType = "ext4";
    };

  fileSystems."/boot" = lib.mkForce
    { device = "/dev/disk/by-uuid/5386-B9AE";
      fsType = "vfat";
    };

  swapDevices = lib.mkForce
    [ { device = "/dev/disk/by-uuid/8924970e-10bd-4d6f-a137-61d05a886106"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
