name: "Rebuild system"

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v30
 
      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: pn
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Build"
        id: fetcher
        run: nix build .#nixosConfigurations.t14.config.system.build.toplevel
